import React from "react";
import {
  Icon as ChakraIcon,
  IconProps as ChakraIconProps,
} from "@chakra-ui/react";
import * as IconComponent from "./components";

export const icons = {
  passwordShow: IconComponent.PasswordShowIcon,
  passwordHide: IconComponent.PasswordHideIcon,
  info: IconComponent.InfoIcon,
  contact: IconComponent.ContactIcon,
  bankAccount: IconComponent.BankAccountIcon,
  email: IconComponent.EmailIcon,
  smile: IconComponent.SmileIcon,
  check: IconComponent.CheckIcon,
  user: IconComponent.UserIcon,
  back: IconComponent.BackIcon,
  menu: IconComponent.MenuIcon,
  address: IconComponent.AddressIcon,
  menuEllipsis: IconComponent.MenuEllipsisIcon,
  menuEllipsisHorizontal: IconComponent.MenuEllipsisHorizontalIcon,
  logout: IconComponent.LogoutIcon,
  arrowDown: IconComponent.ArrowDownIcon,
  arrowUp: IconComponent.ArrowUpIcon,
  arrowLeft: IconComponent.ArrowLeftIcon,
  arrowRight: IconComponent.ArrowRightIcon,
  caretDown: IconComponent.CaretDownIcon,
  caretUp: IconComponent.CaretUpIcon,
  caretLeft: IconComponent.CaretLeftIcon,
  caretRight: IconComponent.CaretRightIcon,
  search: IconComponent.SearchIcon,
  about: IconComponent.AboutIcon,
  video: IconComponent.VideoIcon,
  home: IconComponent.HomeIcon,
  plus: IconComponent.PlusIcon,
  setting: IconComponent.SettingIcon,
  plan: IconComponent.PlanIcon,
  dashboard: IconComponent.DashboardIcon,
  order: IconComponent.OrderIcon,
  cart: IconComponent.CartIcon,
  store: IconComponent.StoreIcon,
  subscription: IconComponent.SubscriptionIcon,
  star: IconComponent.StarIcon,
  starFilled: IconComponent.StarFillIcon,
  starHalf: IconComponent.StarHalfIcon,
  app: IconComponent.AppIcon,
  course: IconComponent.CourseIcon,
  notification: IconComponent.NotificationIcon,
  loading: IconComponent.LoadingIcon,
  wallet: IconComponent.WalletIcon,
  lightMode: IconComponent.LightModeIcon,
  darkMode: IconComponent.DarkModeIcon,
  play: IconComponent.PlayIcon,
  pause: IconComponent.PauseIcon,
  stop: IconComponent.StopIcon,
  muted: IconComponent.VolumeMutedIcon,
  unmuted: IconComponent.VolumeUnmutedIcon,
  fullscreen: IconComponent.FullScreenIcon,
  exitFullscreen: IconComponent.ExitFullScreenIcon,
  pictureInPicture: IconComponent.PictureInPictureIcon,
  exitPictureInPicture: IconComponent.ExitPictureInPictureIcon,
  reload: IconComponent.ReloadIcon,
  error: IconComponent.ErrorIcon,
  circleOutlined: IconComponent.CircleOutlinedIcon,
  ok: IconComponent.OkIcon,
  trash: IconComponent.TrashIcon,
  file: IconComponent.FileIcon,
  invoice: IconComponent.InvoiceIcon,
  edit: IconComponent.EditIcon,
  price: IconComponent.PriceIcon,
  admin: IconComponent.AdminIcon,
  instructor: IconComponent.InstructorIcon,
  domain: IconComponent.DomainIcon,
  storage: IconComponent.StorageIcon,
  product: IconComponent.ProductIcon,
  bold: IconComponent.BoldIcon,
  italic: IconComponent.ItalicIcon,
  undo: IconComponent.UndoIcon,
  redo: IconComponent.RedoIcon,
  heading1: IconComponent.Heading1Icon,
  heading2: IconComponent.Heading2Icon,
  heading3: IconComponent.Heading3Icon,
  heading4: IconComponent.Heading4Icon,
  heading5: IconComponent.Heading5Icon,
  heading6: IconComponent.Heading6Icon,
  password: IconComponent.PasswordIcon,
  filters: IconComponent.FiltersIcon,
  material: IconComponent.MaterialIcon,
  download: IconComponent.DownloadIcon,
  upload: IconComponent.UploadIcon,
  onboarding: IconComponent.OnboardingIcon,
  website: IconComponent.WebsiteIcon,
  feature: IconComponent.FeatureIcon,
  catalog: IconComponent.CatalogIcon,
};

export type IconName = keyof typeof icons;

export interface IconProps extends ChakraIconProps {
  readonly name: IconName;
}

export const Icon: React.FC<IconProps> = ({ children, ...props }) => (
  <ChakraIcon {...props} as={icons[props.name] as any} />
);
